sudo: required
language: python
services:
    - docker
before_install:
    - docker pull armish/pyensembl:0.9.4
script:
    - env
    - echo $TRAVIS_JOB_ID
    - docker build --build-arg TRAVIS_JOB_ID=$TRAVIS_JOB_ID --build-arg PYTHON_VERSION=2 -t "ensembl-test2" .
    - docker build --build-arg TRAVIS_JOB_ID=$TRAVIS_JOB_ID --build-arg PYTHON_VERSION=3 -t "ensembl-test3" .
deploy:
  provider: pypi
  distributions: sdist
  user: hammerlab
  password:
    secure: "X4DhwpPp5OJDhejSLj3y+b/zjGgvKpaVh5DEo68HUoy6GKdTOmy2+QM1/tCQVt9fze5X2E849aNN9kfXUjHoeAd3OvFIzota3Bu6hOq+q2HKj6IB0mjB9p3b3kqDusBh9I/66MXApntrqZdN9ZOm/wjD0KHzGbBdvBz41hePsHw="
  on:
    branch: master
